language: go
go:
  - 1.10.x

cache:
  directories:
  - .gopath

sudo: required

# services:
#   - docker

env:
  - "PATH=/home/travis/gopath/bin:$PATH"

script:
  # - "[ ! -z \"$TRAVIS_TAG\" ] && git describe --tags > .version || echo 'non-tag build'"
  - GOOS=linux GOARCH=amd64 BINSUFFIX=-linux-amd64 make
  - GOOS=linux GOARCH=386 BINSUFFIX=-linux-386 make
  - GOOS=windows GOARCH=amd64 BINSUFFIX=-windows-amd64.exe make
  - GOOS=windows GOARCH=386 BINSUFFIX=-windows-386.exe make
  - GOOS=darwin GOARCH=amd64 BINSUFFIX=-darwin-amd64 make

before_install:
  - curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
  - curl -L https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz --output ghr.tar.gz && tar zxvf ghr.tar.gz

after_script:
  - ghr_v0.12.0_linux_amd64/ghr --username HealthSamurai -r hl7proxy --token $GITHUB_TOKEN --prerelease -replace --debug edge bin/
  # - "[ ! -z \"$TRAVIS_TAG\" ] && ghr_v0.12.0_linux_amd64/ghr --username fhirbase -r fhirbase --token $GITHUB_TOKEN -n $TRAVIS_TAG --debug $TRAVIS_TAG bin/"
